stages:
  - build
  - deploy

jobs:
  include:
    - stage: build
      script:
        - echo toto
    - stage: deploy
      provider: pages
      skip_cleanup: true
      local_dir: __sapper__/export
      github_token: $GITHUB_TOKEN
      keep_history: true
      on:
        branch: master
