language: node_js
node_js:
  - 10

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "1.13.0"
  - export PATH="$HOME/.yarn/bin:$PATH"

stages:
  - build
  - deploy

jobs:
  include:
    - stage: build
      script:
        - yarn run export

deploy
  provider: pages
  skip_cleanup: true
  local_dir: __sapper__/export
  github_token: $GITHUB_TOKEN
  keep_history: true
  if: branch = develop
  on:
    branch: master
