# Site settings
title: David Peicho
description: Computer Science Student
# url: "localhost:3000"

# Urls to avoid hacording paths
img_folder: images/
projects_img_folder: images/projects

username: David Peicho
user_title: Computer Science Student
email: david.peicho@gmail.com
linkedin_username: david-peicho
twitter_username: davidpeicho
github_username: DavidPeicho

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

collections:
  projects:
    output: true
